-- Operational tables for notifications, background jobs, and retention tasks.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN
    CREATE TYPE job_status AS ENUM ('pending', 'processing', 'completed', 'failed');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
    CREATE TYPE notification_status AS ENUM ('queued', 'sent', 'failed');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS job_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  status job_status DEFAULT 'pending',
  run_at TIMESTAMPTZ DEFAULT now(),
  locked_at TIMESTAMPTZ,
  locked_by VARCHAR(100),
  last_error TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_queue_status_run
  ON job_queue(status, run_at);

CREATE TABLE IF NOT EXISTS notification_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel VARCHAR(20) NOT NULL,
  recipient VARCHAR(255) NOT NULL,
  template_name VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  status notification_status DEFAULT 'queued',
  attempts SMALLINT DEFAULT 0,
  last_error TEXT,
  send_after TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_status
  ON notification_outbox(status, created_at);
