CREATE TABLE IF NOT EXISTS escrow_release_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  approved_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  approved_at TIMESTAMPTZ DEFAULT now(),
  status VARCHAR(20) DEFAULT 'approved',
  notes TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_escrow_release_unique
  ON escrow_release_approvals (transaction_id, approved_by);

CREATE TABLE IF NOT EXISTS escrow_reconciliation_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at TIMESTAMPTZ DEFAULT now(),
  status VARCHAR(20) NOT NULL DEFAULT 'ok',
  mismatched_accounts INT DEFAULT 0,
  mismatch_details JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);
