CREATE TABLE IF NOT EXISTS ledger_entry_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_type VARCHAR(50) NOT NULL,
  reference_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES ledger_entry_groups(id) ON DELETE CASCADE,
  account_code VARCHAR(50) NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_group
  ON ledger_entries (group_id);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_account
  ON ledger_entries (account_code);
