ALTER TABLE escrow_transactions
  ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(100);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_escrow_idempotency
  ON escrow_transactions (escrow_account_id, transaction_type, idempotency_key);

CREATE TABLE IF NOT EXISTS fraud_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(50) NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'medium',
  reference_type VARCHAR(50) NOT NULL,
  reference_id BIGINT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_fraud_event
  ON fraud_events (event_type, reference_type, reference_id);
