DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kyc_review_status') THEN
    CREATE TYPE kyc_review_status AS ENUM ('open', 'in_review', 'escalated', 'resolved');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kyc_review_priority') THEN
    CREATE TYPE kyc_review_priority AS ENUM ('low', 'normal', 'high', 'urgent');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS kyc_review_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES identity_documents(id) ON DELETE CASCADE,
  status kyc_review_status DEFAULT 'open',
  priority kyc_review_priority DEFAULT 'normal',
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  sla_due_at TIMESTAMPTZ,
  escalation_level SMALLINT DEFAULT 0,
  escalated_at TIMESTAMPTZ,
  reason TEXT,
  flags JSONB,
  risk_score DECIMAL(3,2),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_kyc_review_document
  ON kyc_review_tasks (document_id);

CREATE INDEX IF NOT EXISTS idx_kyc_review_status
  ON kyc_review_tasks (status, sla_due_at);
