-- Remove deprecated land registry tables (government integration not used).
DROP TABLE IF EXISTS land_registry_fee_rules CASCADE;
DROP TABLE IF EXISTS land_registry_payments CASCADE;
DROP TABLE IF EXISTS land_registry_oppositions CASCADE;
DROP TABLE IF EXISTS land_registry_commission_visits CASCADE;
DROP TABLE IF EXISTS land_registry_publications CASCADE;
DROP TABLE IF EXISTS land_registry_steps CASCADE;
DROP TABLE IF EXISTS land_registry_requests CASCADE;
DROP TABLE IF EXISTS administrative_appeals CASCADE;
DROP TABLE IF EXISTS notary_deeds CASCADE;

DROP TYPE IF EXISTS land_registry_request_type CASCADE;
DROP TYPE IF EXISTS land_registry_status CASCADE;
DROP TYPE IF EXISTS land_registry_step_type CASCADE;
DROP TYPE IF EXISTS land_registry_step_status CASCADE;
DROP TYPE IF EXISTS land_registry_publication_type CASCADE;
DROP TYPE IF EXISTS land_registry_opposition_status CASCADE;
DROP TYPE IF EXISTS appeal_type CASCADE;
DROP TYPE IF EXISTS appeal_status CASCADE;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_document_type') THEN
    CREATE TYPE transaction_document_type AS ENUM (
      'notary_deed',
      'tax_registration_receipt',
      'title_transfer_receipt',
      'payment_receipt',
      'power_of_attorney',
      'other'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS transaction_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  document_type transaction_document_type NOT NULL,
  file_path TEXT NOT NULL,
  file_hash CHAR(64),
  file_size INT,
  mime_type VARCHAR(100),
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  verification_status verification_status DEFAULT 'pending',
  verified_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  verified_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_transaction_documents_transaction
  ON transaction_documents (transaction_id);

CREATE INDEX IF NOT EXISTS idx_transaction_documents_status
  ON transaction_documents (verification_status, created_at);
