DO $$
BEGIN
  BEGIN
    ALTER TYPE user_role_type ADD VALUE IF NOT EXISTS 'notary';
  EXCEPTION
    WHEN duplicate_object THEN NULL;
  END;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'legal_requirement_level'
  ) THEN
    CREATE TYPE legal_requirement_level AS ENUM (
      'not_required',
      'recommended',
      'required'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'transaction_legal_case_type'
  ) THEN
    CREATE TYPE transaction_legal_case_type AS ENUM (
      'standard_sale',
      'foreign_party_sale',
      'succession_sale',
      'corporate_sale',
      'power_of_attorney_sale',
      'encumbered_sale',
      'judgment_execution_sale',
      'off_platform_sale',
      'rental',
      'lease'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'platform_service_type'
  ) THEN
    CREATE TYPE platform_service_type AS ENUM (
      'subscription',
      'featured_listing',
      'verification_bundle',
      'document_vault',
      'professional_lead',
      'developer_workspace',
      'premium_advertising',
      'foreign_buyer_pack'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'service_billing_model'
  ) THEN
    CREATE TYPE service_billing_model AS ENUM (
      'one_off',
      'monthly',
      'yearly'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'service_order_status'
  ) THEN
    CREATE TYPE service_order_status AS ENUM (
      'pending_payment',
      'paid',
      'in_progress',
      'completed',
      'cancelled',
      'refunded'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS notary_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE
    REFERENCES users(id) ON DELETE RESTRICT,
  appointment_number VARCHAR(100) NOT NULL UNIQUE,
  appointment_date DATE NOT NULL,
  office_name VARCHAR(255) NOT NULL,
  office_address TEXT,
  service_regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  languages JSONB NOT NULL DEFAULT '[]'::jsonb,
  consultation_fee DECIMAL(10, 2),
  certificate_path TEXT,
  verification_status verification_status NOT NULL DEFAULT 'pending',
  verified_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS notary_id BIGINT
    REFERENCES users(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS legal_case_type transaction_legal_case_type
    NOT NULL DEFAULT 'standard_sale',
  ADD COLUMN IF NOT EXISTS lawyer_requirement_level legal_requirement_level
    NOT NULL DEFAULT 'recommended',
  ADD COLUMN IF NOT EXISTS notary_requirement_level legal_requirement_level
    NOT NULL DEFAULT 'required',
  ADD COLUMN IF NOT EXISTS foreign_party_involved BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS legal_requirements JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE properties
  ALTER COLUMN platform_fee_percentage SET DEFAULT 0.00;

ALTER TABLE transactions
  ALTER COLUMN platform_fee_percentage SET DEFAULT 0.00;

ALTER TABLE subscription_plans
  ALTER COLUMN transaction_fee_percentage SET DEFAULT 0.00;

UPDATE properties
SET platform_fee_percentage = 0.00,
    platform_fee_amount = COALESCE(platform_fee_amount, 0.00),
    total_price_buyer = COALESCE(price, 0.00)
WHERE COALESCE(platform_fee_percentage, 0.00) <> 0.00
   OR platform_fee_amount IS NULL
   OR total_price_buyer IS NULL;

UPDATE transactions
SET platform_fee_percentage = 0.00,
    platform_fee_amount = 0.00,
    total_amount = property_price + COALESCE(lawyer_fee, 0.00) + COALESCE(legal_fees, 0.00)
WHERE COALESCE(platform_fee_percentage, 0.00) <> 0.00
   OR COALESCE(platform_fee_amount, 0.00) <> 0.00;

UPDATE subscription_plans
SET transaction_fee_percentage = 0.00
WHERE COALESCE(transaction_fee_percentage, 0.00) <> 0.00;

CREATE TABLE IF NOT EXISTS platform_service_catalog (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_code VARCHAR(50) NOT NULL UNIQUE,
  service_name VARCHAR(255) NOT NULL,
  service_type platform_service_type NOT NULL,
  billing_model service_billing_model NOT NULL,
  price_xaf DECIMAL(12, 2) NOT NULL CHECK (price_xaf >= 0),
  target_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  fulfillment_sla_days SMALLINT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  description TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  service_id SMALLINT NOT NULL REFERENCES platform_service_catalog(id) ON DELETE RESTRICT,
  property_id BIGINT REFERENCES properties(id) ON DELETE RESTRICT,
  transaction_id BIGINT REFERENCES transactions(id) ON DELETE RESTRICT,
  status service_order_status NOT NULL DEFAULT 'pending_payment',
  amount_xaf DECIMAL(12, 2) NOT NULL CHECK (amount_xaf >= 0),
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  requested_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  assigned_to_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  fulfilled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO platform_service_catalog (
  service_code,
  service_name,
  service_type,
  billing_model,
  price_xaf,
  target_roles,
  fulfillment_sla_days,
  description,
  metadata
)
VALUES
  (
    'featured_listing_boost',
    'Featured Listing Boost',
    'featured_listing',
    'one_off',
    15000,
    '["seller","agent","landlord"]'::jsonb,
    1,
    'Priority placement for compliant listings in high-demand cities and search results.',
    '{"placement_window_days": 14}'::jsonb
  ),
  (
    'verification_bundle',
    'Property Verification Bundle',
    'verification_bundle',
    'one_off',
    35000,
    '["seller","buyer","agent"]'::jsonb,
    5,
    'Structured pre-sale verification covering document review, registry checks, and workflow coordination.',
    '{"includes_lawyer_triage": true}'::jsonb
  ),
  (
    'document_vault_plus',
    'Document Vault Plus',
    'document_vault',
    'yearly',
    12000,
    '["seller","buyer","lawyer","notary"]'::jsonb,
    1,
    'Encrypted long-term storage for deeds, tax receipts, and transfer evidence with controlled sharing.',
    '{"retention_years": 10}'::jsonb
  ),
  (
    'professional_lead_match',
    'Professional Lead Match',
    'professional_lead',
    'one_off',
    10000,
    '["buyer","seller"]'::jsonb,
    2,
    'Paid introduction workflow for verified lawyers and notaries on complex files.',
    '{"eligible_professionals": ["lawyer","notary"]}'::jsonb
  ),
  (
    'developer_workspace',
    'Developer Workspace',
    'developer_workspace',
    'monthly',
    75000,
    '["seller","agent"]'::jsonb,
    2,
    'Portfolio workspace for developers, agencies, and project sellers with branded inventory tools.',
    '{"bulk_listing_limit": 200}'::jsonb
  ),
  (
    'foreign_buyer_pack',
    'Foreign Buyer Compliance Pack',
    'foreign_buyer_pack',
    'one_off',
    125000,
    '["buyer","seller","lawyer","notary"]'::jsonb,
    7,
    'Workflow support for MINDCAF authorization, visa dossier preparation, and compliant closing coordination.',
    '{"mindcaf_visa": true}'::jsonb
  ),
  (
    'premium_ad_slot',
    'Premium Campaign Slot',
    'premium_advertising',
    'monthly',
    50000,
    '["seller","agent","landlord"]'::jsonb,
    1,
    'Sponsored placement package for verified listings, agencies, and rental campaigns.',
    '{"channels": ["web","mobile"]}'::jsonb
  )
ON CONFLICT (service_code) DO UPDATE SET
  service_name = EXCLUDED.service_name,
  service_type = EXCLUDED.service_type,
  billing_model = EXCLUDED.billing_model,
  price_xaf = EXCLUDED.price_xaf,
  target_roles = EXCLUDED.target_roles,
  fulfillment_sla_days = EXCLUDED.fulfillment_sla_days,
  is_active = EXCLUDED.is_active,
  description = EXCLUDED.description,
  metadata = EXCLUDED.metadata,
  updated_at = now();

CREATE INDEX IF NOT EXISTS idx_notary_profiles_status
  ON notary_profiles (verification_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_transactions_legal_case
  ON transactions (legal_case_type, transaction_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_service_catalog_type
  ON platform_service_catalog (service_type, is_active);

CREATE INDEX IF NOT EXISTS idx_service_orders_user
  ON service_orders (user_id, status, created_at DESC);
