DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'notification_outbox'
      AND column_name = 'user_id'
  ) THEN
    ALTER TABLE notification_outbox
      ADD COLUMN user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      ADD COLUMN subject VARCHAR(255),
      ADD COLUMN body_text TEXT,
      ADD COLUMN body_html TEXT,
      ADD COLUMN locale VARCHAR(10),
      ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      ADD COLUMN provider_name VARCHAR(50),
      ADD COLUMN provider_message_id VARCHAR(255);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notification_outbox_user_status
  ON notification_outbox (user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_send_after
  ON notification_outbox (status, send_after, created_at);

CREATE TABLE IF NOT EXISTS in_app_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_type VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'info',
  category VARCHAR(50) NOT NULL DEFAULT 'activity',
  action_url VARCHAR(500),
  action_label VARCHAR(100),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'unread',
  read_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (severity IN ('info', 'success', 'warning', 'critical')),
  CHECK (status IN ('unread', 'read', 'archived'))
);

CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user_status
  ON in_app_notifications (user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_in_app_notifications_expires
  ON in_app_notifications (expires_at);

CREATE TABLE IF NOT EXISTS push_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  push_provider VARCHAR(50) NOT NULL DEFAULT 'generic',
  platform VARCHAR(20) NOT NULL,
  device_token TEXT NOT NULL,
  device_name VARCHAR(255),
  locale VARCHAR(10),
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, device_token),
  CHECK (platform IN ('android', 'ios', 'web', 'desktop'))
);

CREATE INDEX IF NOT EXISTS idx_push_devices_user_active
  ON push_devices (user_id, is_active, last_seen_at DESC);

INSERT INTO email_templates (
  template_name,
  subject_en,
  subject_fr,
  body_en,
  body_fr,
  variables,
  attachments,
  is_active
)
VALUES
  (
    'welcome',
    'Welcome to Real Estate Secure',
    'Bienvenue sur Real Estate Secure',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="background:linear-gradient(135deg,#163328,#1e5a43,#b68a3d);padding:32px 36px;color:#ffffff;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;opacity:0.9;">Real Estate Secure</div>
                <h1 style="margin:14px 0 0;font-size:28px;line-height:1.2;">Welcome, {{first_name}}</h1>
                <p style="margin:12px 0 0;font-size:16px;line-height:1.6;color:rgba(255,255,255,0.92);">
                  Your secure property workspace is ready. We coordinate verified listings, evidence-backed closings,
                  and trusted communication for Cameroon-focused real estate transactions.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:32px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Start with these essentials:
                </p>
                <ul style="margin:0 0 24px;padding-left:20px;font-size:15px;line-height:1.7;color:#415046;">
                  <li>Complete your profile and KYC review.</li>
                  <li>Enable notification preferences that suit your workflow.</li>
                  <li>Use verified conversations and document trails for every serious deal.</li>
                </ul>
                <p style="margin:0;font-size:15px;line-height:1.7;">
                  Need help? Our operations team is structured to support notary-led, evidence-first transactions without
                  pretending to replace the state process.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:24px 36px;background:#fbf8f1;border-top:1px solid #efe5d5;font-size:13px;line-height:1.6;color:#6a6f67;">
                This message was sent by Real Estate Secure. Keep this email for your records.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="background:linear-gradient(135deg,#163328,#1e5a43,#b68a3d);padding:32px 36px;color:#ffffff;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;opacity:0.9;">Real Estate Secure</div>
                <h1 style="margin:14px 0 0;font-size:28px;line-height:1.2;">Bienvenue, {{first_name}}</h1>
                <p style="margin:12px 0 0;font-size:16px;line-height:1.6;color:rgba(255,255,255,0.92);">
                  Votre espace immobilier sécurisé est prêt. Nous coordonnons des annonces vérifiées, des clôtures fondées sur les preuves
                  et des échanges fiables pour les transactions immobilières au Cameroun.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:32px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Commencez par ces étapes:
                </p>
                <ul style="margin:0 0 24px;padding-left:20px;font-size:15px;line-height:1.7;color:#415046;">
                  <li>Complétez votre profil et votre vérification KYC.</li>
                  <li>Activez les préférences de notification adaptées à votre activité.</li>
                  <li>Utilisez les conversations vérifiées et les traces documentaires pour chaque opération sérieuse.</li>
                </ul>
                <p style="margin:0;font-size:15px;line-height:1.7;">
                  Besoin d'aide? Notre équipe d'opérations soutient les transactions pilotées par le notaire et appuyées par des preuves,
                  sans prétendre remplacer les procédures de l'État.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:24px 36px;background:#fbf8f1;border-top:1px solid #efe5d5;font-size:13px;line-height:1.6;color:#6a6f67;">
                Ce message a été envoyé par Real Estate Secure. Conservez cet email pour vos archives.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["first_name"]'::jsonb,
    '[]'::jsonb,
    true
  ),
  (
    'kyc_submission_received',
    'KYC documents received',
    'Documents KYC reçus',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">KYC Intake</div>
                <h1 style="margin:10px 0 0;font-size:26px;">We received your documents</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Hello {{first_name}}, your {{document_type}} submission is now in review.
                </p>
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Reference: <strong>{{document_number}}</strong><br />
                  Status: <strong>{{status_label}}</strong>
                </p>
                <p style="margin:0;font-size:15px;line-height:1.7;">
                  We will notify you if additional evidence is needed or when the review outcome is ready.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Vérification KYC</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Nous avons reçu vos documents</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Bonjour {{first_name}}, votre dossier {{document_type}} est maintenant en cours d'examen.
                </p>
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Référence: <strong>{{document_number}}</strong><br />
                  Statut: <strong>{{status_label}}</strong>
                </p>
                <p style="margin:0;font-size:15px;line-height:1.7;">
                  Nous vous informerons si des preuves supplémentaires sont requises ou lorsque l'issue de l'examen sera disponible.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["first_name","document_type","document_number","status_label"]'::jsonb,
    '[]'::jsonb,
    true
  ),
  (
    'message_received',
    'New message from {{sender_name}}',
    'Nouveau message de {{sender_name}}',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Conversations</div>
                <h1 style="margin:10px 0 0;font-size:26px;">New message from {{sender_name}}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Conversation: <strong>{{conversation_title}}</strong>
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:15px;line-height:1.7;color:#415046;">
                  {{message_preview}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  Open the platform inbox to respond and keep the evidence trail complete.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Messagerie</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Nouveau message de {{sender_name}}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Conversation: <strong>{{conversation_title}}</strong>
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:15px;line-height:1.7;color:#415046;">
                  {{message_preview}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  Ouvrez la boîte de réception de la plateforme pour répondre et conserver une trace complète.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["sender_name","conversation_title","message_preview"]'::jsonb,
    '[]'::jsonb,
    true
  ),
  (
    'transaction_stage_update',
    'Transaction update: {{stage_label}}',
    'Mise à jour transaction: {{stage_label}}',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Transaction Workflow</div>
                <h1 style="margin:10px 0 0;font-size:26px;">{{stage_label}}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Transaction <strong>{{transaction_number}}</strong> for <strong>{{property_title}}</strong> has moved to the next step.
                </p>
                <p style="margin:0;font-size:15px;line-height:1.7;">{{summary_line}}</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Workflow transactionnel</div>
                <h1 style="margin:10px 0 0;font-size:26px;">{{stage_label}}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  La transaction <strong>{{transaction_number}}</strong> pour <strong>{{property_title}}</strong> a franchi une nouvelle étape.
                </p>
                <p style="margin:0;font-size:15px;line-height:1.7;">{{summary_line}}</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["stage_label","transaction_number","property_title","summary_line"]'::jsonb,
    '[]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET subject_en = EXCLUDED.subject_en,
    subject_fr = EXCLUDED.subject_fr,
    body_en = EXCLUDED.body_en,
    body_fr = EXCLUDED.body_fr,
    variables = EXCLUDED.variables,
    attachments = EXCLUDED.attachments,
    is_active = EXCLUDED.is_active,
    updated_at = now();

INSERT INTO sms_templates (
  template_name,
  body_en,
  body_fr,
  variables,
  is_active
)
VALUES
  (
    'kyc_submission_received',
    'Real Estate Secure: your {{document_type}} KYC file {{document_number}} is now under review.',
    'Real Estate Secure: votre dossier KYC {{document_type}} {{document_number}} est en cours d''examen.',
    '["document_type","document_number"]'::jsonb,
    true
  ),
  (
    'message_received',
    'Real Estate Secure: new message from {{sender_name}} in {{conversation_title}}.',
    'Real Estate Secure: nouveau message de {{sender_name}} dans {{conversation_title}}.',
    '["sender_name","conversation_title"]'::jsonb,
    true
  ),
  (
    'transaction_stage_update',
    'Real Estate Secure: transaction {{transaction_number}} moved to {{stage_label}}.',
    'Real Estate Secure: la transaction {{transaction_number}} est passée à l''étape {{stage_label}}.',
    '["transaction_number","stage_label"]'::jsonb,
    true
  ),
  (
    'dispute_escalated',
    'Real Estate Secure: dispute {{dispute_number}} has been escalated for review.',
    'Real Estate Secure: le litige {{dispute_number}} a été transmis pour examen.',
    '["dispute_number"]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET body_en = EXCLUDED.body_en,
    body_fr = EXCLUDED.body_fr,
    variables = EXCLUDED.variables,
    is_active = EXCLUDED.is_active,
    updated_at = now();
