CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS refresh_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_family_id UUID NOT NULL,
  parent_session_id BIGINT REFERENCES refresh_sessions(id) ON DELETE SET NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  device_id VARCHAR(128),
  device_name VARCHAR(255),
  platform VARCHAR(50),
  app_version VARCHAR(50),
  ip_address INET,
  user_agent TEXT,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL,
  rotated_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoke_reason TEXT,
  replaced_by_id BIGINT REFERENCES refresh_sessions(id) ON DELETE SET NULL,
  compromised_at TIMESTAMPTZ,
  is_forced_logout BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refresh_sessions_user
  ON refresh_sessions (user_id, revoked_at, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_refresh_sessions_family
  ON refresh_sessions (session_family_id, revoked_at, expires_at DESC);

CREATE TABLE IF NOT EXISTS api_idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_key VARCHAR(255) NOT NULL UNIQUE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  request_method VARCHAR(10) NOT NULL,
  request_path TEXT NOT NULL,
  request_hash CHAR(64) NOT NULL,
  response_status SMALLINT,
  response_body JSONB,
  locked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_api_idempotency_user
  ON api_idempotency_keys (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS uploaded_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  category VARCHAR(50) NOT NULL,
  visibility VARCHAR(30) NOT NULL DEFAULT 'private',
  storage_driver VARCHAR(30) NOT NULL,
  bucket_name VARCHAR(255),
  object_key TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  detected_mime_type VARCHAR(100),
  original_file_name VARCHAR(255) NOT NULL,
  file_ext VARCHAR(20),
  file_size INT NOT NULL CHECK (file_size >= 0),
  file_hash CHAR(64) NOT NULL,
  malware_scan_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  malware_scan_notes TEXT,
  watermark_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  redaction_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_uploaded_assets_owner
  ON uploaded_assets (owner_user_id, category, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_uploaded_assets_hash
  ON uploaded_assets (file_hash, created_at DESC);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS profile_image_asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE identity_documents
  ADD COLUMN IF NOT EXISTS front_image_asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS back_image_asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS portrait_image_asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE property_documents
  ADD COLUMN IF NOT EXISTS asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE property_images
  ADD COLUMN IF NOT EXISTS original_asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE transaction_documents
  ADD COLUMN IF NOT EXISTS asset_id BIGINT REFERENCES uploaded_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE transaction_offline_steps
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE transaction_legal_cases
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE disputes
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0;

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS commercial_close_status VARCHAR(40) NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS notarial_execution_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS title_confirmation_status VARCHAR(40) NOT NULL DEFAULT 'pending';

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS row_version INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS commercial_close_status VARCHAR(40) NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS notarial_execution_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS title_confirmation_status VARCHAR(40) NOT NULL DEFAULT 'pending';

ALTER TABLE properties
  DROP CONSTRAINT IF EXISTS chk_properties_commercial_close_status,
  DROP CONSTRAINT IF EXISTS chk_properties_notarial_execution_status,
  DROP CONSTRAINT IF EXISTS chk_properties_title_confirmation_status;

ALTER TABLE properties
  ADD CONSTRAINT chk_properties_commercial_close_status
    CHECK (commercial_close_status IN ('open', 'agreed', 'commercially_closed', 'cancelled')),
  ADD CONSTRAINT chk_properties_notarial_execution_status
    CHECK (notarial_execution_status IN ('pending', 'in_progress', 'notarial_deed_signed', 'filed', 'blocked')),
  ADD CONSTRAINT chk_properties_title_confirmation_status
    CHECK (title_confirmation_status IN ('pending', 'mutation_filed', 'title_transfer_confirmed', 'blocked'));

ALTER TABLE transactions
  DROP CONSTRAINT IF EXISTS chk_transactions_commercial_close_status,
  DROP CONSTRAINT IF EXISTS chk_transactions_notarial_execution_status,
  DROP CONSTRAINT IF EXISTS chk_transactions_title_confirmation_status;

ALTER TABLE transactions
  ADD CONSTRAINT chk_transactions_commercial_close_status
    CHECK (commercial_close_status IN ('open', 'agreed', 'commercially_closed', 'cancelled')),
  ADD CONSTRAINT chk_transactions_notarial_execution_status
    CHECK (notarial_execution_status IN ('pending', 'in_progress', 'notarial_deed_signed', 'filed', 'blocked')),
  ADD CONSTRAINT chk_transactions_title_confirmation_status
    CHECK (title_confirmation_status IN ('pending', 'mutation_filed', 'title_transfer_confirmed', 'blocked'));

CREATE TABLE IF NOT EXISTS outbox_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic VARCHAR(100) NOT NULL,
  aggregate_type VARCHAR(50) NOT NULL,
  aggregate_id VARCHAR(255) NOT NULL,
  event_key VARCHAR(255) NOT NULL UNIQUE,
  payload JSONB NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ,
  failure_reason TEXT,
  attempts INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_status
  ON outbox_events (status, available_at, created_at);
