CREATE TABLE IF NOT EXISTS user_action_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  action_type VARCHAR(50) NOT NULL,
  delivery_channel VARCHAR(20) NOT NULL,
  target_value_encrypted TEXT,
  target_value_hash CHAR(64),
  token_hash CHAR(64),
  code_hash CHAR(64),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (action_type IN ('email_verification', 'password_reset', 'phone_verification')),
  CHECK (delivery_channel IN ('email', 'sms', 'in_app')),
  CHECK (token_hash IS NOT NULL OR code_hash IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_user_action_tokens_user_action
  ON user_action_tokens (user_id, action_type, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_action_tokens_target
  ON user_action_tokens (target_value_hash, action_type, expires_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_action_tokens_token_hash
  ON user_action_tokens (token_hash, action_type)
  WHERE token_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_action_tokens_code_hash
  ON user_action_tokens (code_hash, action_type)
  WHERE code_hash IS NOT NULL;

INSERT INTO email_templates (
  template_name,
  subject_en,
  subject_fr,
  body_en,
  body_fr,
  variables,
  attachments,
  is_active
)
VALUES
  (
    'email_verification',
    'Verify your Real Estate Secure email address',
    'Vérifiez votre adresse e-mail Real Estate Secure',
    '<p>Hello {{first_name}},</p><p>Use this link to verify your email address and keep your secure property workspace active:</p><p><a href="{{verification_url}}">Verify email address</a></p><p>If you did not request this action, you can safely ignore this message.</p>',
    '<p>Bonjour {{first_name}},</p><p>Utilisez ce lien pour vérifier votre adresse e-mail et sécuriser votre espace Real Estate Secure :</p><p><a href="{{verification_url}}">Vérifier mon adresse e-mail</a></p><p>Si vous n’êtes pas à l’origine de cette action, ignorez simplement ce message.</p>',
    '["first_name","verification_url"]'::jsonb,
    '[]'::jsonb,
    true
  ),
  (
    'password_reset',
    'Reset your Real Estate Secure password',
    'Réinitialisez votre mot de passe Real Estate Secure',
    '<p>Hello,</p><p>We received a request to reset your password. Use this link to continue:</p><p><a href="{{reset_url}}">Reset password</a></p><p>This link expires soon for your security.</p>',
    '<p>Bonjour,</p><p>Nous avons reçu une demande de réinitialisation de mot de passe. Utilisez ce lien pour continuer :</p><p><a href="{{reset_url}}">Réinitialiser le mot de passe</a></p><p>Ce lien expire rapidement pour votre sécurité.</p>',
    '["reset_url"]'::jsonb,
    '[]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET
  subject_en = EXCLUDED.subject_en,
  subject_fr = EXCLUDED.subject_fr,
  body_en = EXCLUDED.body_en,
  body_fr = EXCLUDED.body_fr,
  variables = EXCLUDED.variables,
  attachments = EXCLUDED.attachments,
  is_active = EXCLUDED.is_active,
  updated_at = now();

INSERT INTO sms_templates (
  template_name,
  body_en,
  body_fr,
  variables,
  is_active
)
VALUES
  (
    'phone_verification',
    'Your Real Estate Secure code is {{code}}. It expires in 10 minutes.',
    'Votre code Real Estate Secure est {{code}}. Il expire dans 10 minutes.',
    '["code"]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET
  body_en = EXCLUDED.body_en,
  body_fr = EXCLUDED.body_fr,
  variables = EXCLUDED.variables,
  is_active = EXCLUDED.is_active,
  updated_at = now();
