CREATE TABLE IF NOT EXISTS auth_action_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action_type VARCHAR(40) NOT NULL,
  token_hash CHAR(64),
  code_hash CHAR(64),
  target_value TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  max_attempts SMALLINT NOT NULL DEFAULT 5,
  attempt_count SMALLINT NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoke_reason VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (action_type IN ('email_verification', 'password_reset', 'phone_verification')),
  CHECK (max_attempts >= 1),
  CHECK (attempt_count >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_action_tokens_token_hash
  ON auth_action_tokens (token_hash)
  WHERE token_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_auth_action_tokens_user_action_active
  ON auth_action_tokens (user_id, action_type, created_at DESC)
  WHERE consumed_at IS NULL
    AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_auth_action_tokens_code_lookup
  ON auth_action_tokens (user_id, action_type, code_hash, created_at DESC)
  WHERE code_hash IS NOT NULL
    AND consumed_at IS NULL
    AND revoked_at IS NULL;

INSERT INTO email_templates (
  template_name,
  subject_en,
  subject_fr,
  body_en,
  body_fr,
  variables,
  attachments,
  is_active
)
VALUES
  (
    'password_reset',
    'Reset your Real Estate Secure password',
    'Reinitialisez votre mot de passe Real Estate Secure',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Security</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Reset your password</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Hello {{first_name}}, we received a request to reset the password for your Real Estate Secure account.
                </p>
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Use this secure token in the app or follow your internal reset flow:
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:16px;line-height:1.7;color:#163328;font-weight:700;">
                  {{reset_token}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  This token expires at {{expires_at}}. If you did not request this change, ignore this message and review your account activity.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Securite</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Reinitialisez votre mot de passe</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Bonjour {{first_name}}, nous avons recu une demande de reinitialisation pour votre compte Real Estate Secure.
                </p>
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Utilisez ce jeton securise dans l'application ou dans votre flux de reinitialisation:
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:16px;line-height:1.7;color:#163328;font-weight:700;">
                  {{reset_token}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  Ce jeton expire a {{expires_at}}. Si vous n'avez pas demande ce changement, ignorez ce message et verifiez l'activite de votre compte.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["first_name","reset_token","expires_at"]'::jsonb,
    '[]'::jsonb,
    true
  ),
  (
    'email_verification',
    'Verify your Real Estate Secure email',
    'Verifiez votre adresse email Real Estate Secure',
    $$<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Account Verification</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Confirm your email address</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Hello {{first_name}}, use the verification token below to confirm {{email_address}}.
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:16px;line-height:1.7;color:#163328;font-weight:700;">
                  {{verification_token}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  This token expires at {{expires_at}}.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    $$<!DOCTYPE html>
<html lang="fr">
  <body style="margin:0;background:#f5efe4;font-family:Segoe UI,Arial,sans-serif;color:#163328;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e4d9c5;">
            <tr>
              <td style="padding:32px 36px;border-bottom:1px solid #efe5d5;">
                <div style="font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:#1e5a43;">Verification du compte</div>
                <h1 style="margin:10px 0 0;font-size:26px;">Confirmez votre adresse email</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px;">
                <p style="margin:0 0 16px;font-size:15px;line-height:1.7;">
                  Bonjour {{first_name}}, utilisez le jeton ci-dessous pour confirmer {{email_address}}.
                </p>
                <div style="padding:18px 20px;border-radius:18px;background:#f8f4eb;border:1px solid #eadfcf;font-size:16px;line-height:1.7;color:#163328;font-weight:700;">
                  {{verification_token}}
                </div>
                <p style="margin:16px 0 0;font-size:14px;line-height:1.7;color:#6a6f67;">
                  Ce jeton expire a {{expires_at}}.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>$$,
    '["first_name","email_address","verification_token","expires_at"]'::jsonb,
    '[]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET subject_en = EXCLUDED.subject_en,
    subject_fr = EXCLUDED.subject_fr,
    body_en = EXCLUDED.body_en,
    body_fr = EXCLUDED.body_fr,
    variables = EXCLUDED.variables,
    attachments = EXCLUDED.attachments,
    is_active = EXCLUDED.is_active,
    updated_at = now();

INSERT INTO sms_templates (
  template_name,
  body_en,
  body_fr,
  variables,
  is_active
)
VALUES
  (
    'phone_verification_code',
    'Real Estate Secure verification code: {{verification_code}}. Expires at {{expires_at}}.',
    'Code de verification Real Estate Secure: {{verification_code}}. Expire a {{expires_at}}.',
    '["verification_code","expires_at"]'::jsonb,
    true
  )
ON CONFLICT (template_name) DO UPDATE
SET body_en = EXCLUDED.body_en,
    body_fr = EXCLUDED.body_fr,
    variables = EXCLUDED.variables,
    is_active = EXCLUDED.is_active,
    updated_at = now();
