CREATE TABLE IF NOT EXISTS subscription_checkout_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference VARCHAR(120) UNIQUE NOT NULL,
  provider VARCHAR(40) NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  plan_id SMALLINT NOT NULL REFERENCES subscription_plans(id) ON DELETE RESTRICT,
  subscription_id BIGINT REFERENCES user_subscriptions(id) ON DELETE SET NULL,
  billing_cycle billing_cycle NOT NULL,
  amount DECIMAL(10, 2) NOT NULL CHECK (amount >= 0),
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  session_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  provider_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  checkout_url TEXT,
  provider_checkout_id VARCHAR(120),
  callback_url TEXT,
  redirect_url TEXT,
  customer_email VARCHAR(255),
  customer_name VARCHAR(255),
  provider_payload JSONB,
  error_message TEXT,
  paid_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscription_checkout_sessions_user_id
  ON subscription_checkout_sessions(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_subscription_checkout_sessions_status
  ON subscription_checkout_sessions(session_status, provider_status, created_at DESC);
