CREATE TABLE IF NOT EXISTS kyc_provider_cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider VARCHAR(40) NOT NULL DEFAULT 'sumsub',
  external_user_id VARCHAR(255) NOT NULL,
  provider_applicant_id VARCHAR(255),
  inspection_id VARCHAR(255),
  level_name VARCHAR(120) NOT NULL,
  verification_status verification_status NOT NULL DEFAULT 'pending',
  provider_review_status VARCHAR(64) NOT NULL DEFAULT 'init',
  provider_review_answer VARCHAR(32),
  provider_review_reject_type VARCHAR(32),
  latest_event_type VARCHAR(96),
  moderation_comment TEXT,
  client_comment TEXT,
  rejection_labels JSONB,
  raw_provider_payload JSONB,
  provider_metadata JSONB,
  access_token_expires_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_event_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  row_version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_kyc_provider_case_user_provider
  ON kyc_provider_cases (user_id, provider);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_kyc_provider_case_provider_external_user
  ON kyc_provider_cases (provider, external_user_id);

CREATE INDEX IF NOT EXISTS idx_kyc_provider_case_status
  ON kyc_provider_cases (verification_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_kyc_provider_case_applicant
  ON kyc_provider_cases (provider_applicant_id, inspection_id);

CREATE TABLE IF NOT EXISTS kyc_provider_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_case_id BIGINT REFERENCES kyc_provider_cases(id) ON DELETE CASCADE,
  provider VARCHAR(40) NOT NULL,
  correlation_id VARCHAR(255) NOT NULL,
  event_type VARCHAR(96) NOT NULL,
  applicant_id VARCHAR(255),
  inspection_id VARCHAR(255),
  external_user_id VARCHAR(255),
  review_status VARCHAR(64),
  review_answer VARCHAR(32),
  review_reject_type VARCHAR(32),
  payload JSONB NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_kyc_provider_event_provider_correlation
  ON kyc_provider_events (provider, correlation_id);

