INSERT INTO subscription_plans (
  plan_name,
  plan_code,
  price_monthly,
  price_yearly,
  currency,
  max_listings,
  max_photos_per_listing,
  max_videos_per_listing,
  featured_listings_included,
  transaction_fee_percentage,
  priority_support,
  analytics_access,
  api_access,
  bulk_listing_tools,
  company_profile,
  badge_display,
  is_active,
  sort_order,
  description,
  features
)
VALUES
  (
    'Free',
    'free',
    0,
    NULL,
    'XAF',
    1,
    5,
    0,
    0,
    0.0,
    false,
    false,
    false,
    false,
    false,
    NULL,
    true,
    1,
    'Starter access for individual buyers and sellers.',
    '["Basic listings","Standard support","Access to paid verification and promotion services"]'::jsonb
  ),
  (
    'Basic',
    'basic',
    5000,
    50000,
    'XAF',
    3,
    10,
    0,
    0,
    0.0,
    false,
    true,
    false,
    false,
    false,
    'verified',
    true,
    2,
    'For independent sellers and small property managers.',
    '["Priority verification queue","Analytics dashboard","Email support","Discounted listing boosts"]'::jsonb
  ),
  (
    'Standard',
    'standard',
    10000,
    100000,
    'XAF',
    6,
    15,
    1,
    1,
    0.0,
    true,
    true,
    false,
    true,
    true,
    'premium',
    true,
    3,
    'Growing teams and multi-property sellers.',
    '["Featured listing credits","Priority support","Market insights","Document vault access"]'::jsonb
  ),
  (
    'Professional',
    'pro',
    20000,
    200000,
    'XAF',
    12,
    20,
    3,
    3,
    0.0,
    true,
    true,
    true,
    true,
    true,
    'pro',
    true,
    4,
    'High-volume sellers and developers.',
    '["API access","Dedicated success manager","Bulk tools","Developer workspace discount"]'::jsonb
  )
ON CONFLICT (plan_code) DO UPDATE SET
  plan_name = EXCLUDED.plan_name,
  price_monthly = EXCLUDED.price_monthly,
  price_yearly = EXCLUDED.price_yearly,
  currency = EXCLUDED.currency,
  max_listings = EXCLUDED.max_listings,
  max_photos_per_listing = EXCLUDED.max_photos_per_listing,
  max_videos_per_listing = EXCLUDED.max_videos_per_listing,
  featured_listings_included = EXCLUDED.featured_listings_included,
  transaction_fee_percentage = EXCLUDED.transaction_fee_percentage,
  priority_support = EXCLUDED.priority_support,
  analytics_access = EXCLUDED.analytics_access,
  api_access = EXCLUDED.api_access,
  bulk_listing_tools = EXCLUDED.bulk_listing_tools,
  company_profile = EXCLUDED.company_profile,
  badge_display = EXCLUDED.badge_display,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  description = EXCLUDED.description,
  features = EXCLUDED.features;
